version: '1'

setup:
  image: ibmcom/pipeline-base-image:2.7
  script: |
    #!/usr/bin/env bash

    npm ci

test:
  abort_on_failure: false
  image: ibmcom/pipeline-base-image:2.7
  script: |
    #!/usr/bin/env bash

    npm test

containerize:
  dind: true
  image: ibmcom/pipeline-base-image:2.6
  script: |
    #!/usr/bin/env bash

    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi

    source scripts/build_setup.sh
    source scripts/build.sh

deploy:
  image: ibmcom/pipeline-base-image:2.6
  script: |
    #!/usr/bin/env bash

    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi

    source scripts/deploy_setup.sh
    source scripts/deploy.sh

acceptance-test:
  abort_on_failure: false
  image: ibmcom/pipeline-base-image:2.7
  script: |
    #!/usr/bin/env bash

    source /root/.nvm/nvm.sh
    npm ci
    export APP_URL=$(cat ../app-url)
    npm run acceptance-test
