repos:
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.61.dss
    hooks:
      - id: detect-secrets # pragma: whitelist secret
        args: [--baseline, .secrets.baseline, --use-all-plugins]